### PR TITLE
Rename propagators and associated variables

### PR DESCRIPTION
**Pull request by akorgor**
This PR proposes renaming the propagators and the associated state variables to improve readability and clarity, especially in the line `S_.v_ = ...`, which updates the membrane voltage and in the `gradient_change` function.

The legacy `y0` and `y3` variables might be confusing in the e-prop context where $y$ denotes the predictions and $y^*$ the targets.

Renaming `y0` to `i_in` would improve consistency with `I_e` and renaming `y3` to `v` with `V_m`.

`P33` represents the propagator matrix entry in the third row and third column. However, the exact position of the entry depends on the order of the entries in the `y` variable, which is arbitrary and thus makes the position `33` arbitrary, too. This PR suggests decoupling the propagator names from the positions in the legacy matrix and basing their names rather on their purpose, e.g., `P_v` propagating the `v` term.

For additional symmetry with this new formulation,
```cpp
S_.v_ -= P_.V_th_ * S_.z_;
```
could be rewritten as
```cpp
V_.P_z = -P_.V_th_;
(...)
S_.v_ = (...) + V_.P_z_ * S_.z_;
```
However, this might reduce clarity again.

### CODE REVIEW

**Comment by JesusEV** [comment]
@akorgor That last suggestion to include additional symmetry isn't something that is already implemented, is it?  Could you  tell me more about `V_.P_z = -P_.V_th_;` I think I do not follow it

**Comment by JesusEV** [comment]
> @akorgor That last suggestion to include additional symmetry isn't something that is already implemented, is it? Could you tell me more about `V_.P_z = -P_.V_th_;` I think I do not follow it

Ok the idea involves a temporary modification of the propagator in such a way that V_.P_z_ * S_.z_ would already include the subtraction of the threshold potential. Is this correct? If so, this adjustment might make the formulation somewhat more difficult to understand, I believe

**Comment by akorgor** [comment]
> @akorgor That last suggestion to include additional symmetry isn't something that is already implemented, is it? Could you tell me more about `V_.P_z = -P_.V_th_;` I think I do not follow it
 

Exactly. It is a change I did not include in the change set because I was concerned that it would trade symmetry for readability. However, I still wanted to mention it in case you had a different opinion.

> Ok the idea involves a temporary modification of the propagator in such a way that V_.P_z_ * S_.z_ would already include the subtraction of the threshold potential. Is this correct? If so, this adjustment might make the formulation somewhat more difficult to understand, I believe

Maybe the code snippet becomes more clear with a bit more context:
```cpp

eprop_readout::pre_run_hook()
{
  (...)
  V_.P_v_ = ...
  V_.P_i_in_ =...
  V_.P_z_in_ = ...
  V_.P_z_ =-V_th;
}

eprop_readout::update()
{
 (...)
 S_.v_ = V_.P_i_in_ * S_.i_in_ + V_.P_z_in_ * S_.z_in_ + V_.P_v_ * S_.v_ + V_.P_z_ * S_.z_;
 (...)
}
```
With symmetry, I mean that for each term that contributes to the membrane voltage, there is a propagator, i.e., 
`P_.propagator * S_.variable`

But I would be fine with dropping it, since with the old formulation, the reset upon a spike is more apparent.

**Comment by JesusEV** [comment]
> ```c++
>  S_.v_ = V_.P_i_in_ * S_.i_in_ + V_.P_z_in_ * S_.z_in_ + V_.P_v_ * S_.v_ + V_.P_z_ * S_.z_;
> ```

@akorgor Now I understand what you mean, I was confusing `V_.P_z_in_` with `V_.P_z_`.  I understand now what you mean by the improved symmetry. 

However there are 2 reasons why I disagree with the change:

- `V_.P_z_` does not have the same physical origin as the other propagators, which by the way play their role only in subthreshold dynamics. The notation would suggest that `V_.P_z_` is in the same category, which would also obscure the subthreshold/threshold separation.

- The potential benefits of symmetry and readability do not outweigh the potential complaints, in my opinion.

**Comment by JesusEV** [comment]
The new variable names are very convenient because they unify and make explicit the relationship between state variables and  the different propagators and also take a healthy step away from legacy names. I think that, if there are no more suggestions from others, the PR should be merged.

**Pull request merged**
